window.TRIP_DATA = {
  itinerary: [
    { day: 1, date: "Sat, 21 Nov", stay: "Taipei", moving: true, title: "Arrive and settle in", plan: "Evening arrival, hotel check-in, neighbourhood walk and convenience-store supper.", travel: "Flight · SIN → TPE · CI754 · 14:25–19:05", note: "Jasper Young Hotel Banqiao is confirmed for this night." },
    { day: 2, date: "Sun, 22 Nov", stay: "Hualien", moving: true, title: "East by train", plan: "Unhurried breakfast, TRA to Hualien, explore locally and visit Dongdamen Night Market.", travel: "TRA · Taipei/Banqiao → Hualien · exact train TBD", note: "Reserve four seats when ticket sales open." },
    { day: 3, date: "Mon, 23 Nov", stay: "Hualien", moving: false, title: "Pacific coast day", plan: "Qixingtan, Shitiping and a fresh seafood meal. Whale or dolphin watching only if sea conditions are suitable.", travel: "Local taxi, rental car or private hire · choice TBD", note: "Qixingtan and Shitiping are distinct experiences but far apart; route timing needs refinement." },
    { day: 4, date: "Tue, 24 Nov", stay: "Chishang", moving: true, title: "Into rice country", plan: "TRA south, check in, cycle Brown Boulevard and enjoy Chishang bento.", travel: "TRA · Hualien → Chishang · exact train TBD", note: "Cycling duration and luggage arrangements remain flexible." },
    { day: 5, date: "Wed, 25 Nov", stay: "Chishang", moving: false, title: "A slow countryside day", plan: "More cycling, rice-field light, local snacks and free time for an unplanned discovery.", travel: "Bicycle / walking", note: "Accommodation not yet confirmed." },
    { day: 6, date: "Thu, 26 Nov", stay: "Taitung", moving: true, title: "Ranch and highland", plan: "Short train to Taitung. Chulu Ranch and Luye Highland are proposed; sequence depends on transport.", travel: "TRA · Chishang → Taitung · then car/private hire", note: "Taitung-area accommodation and vehicle plan are tentative." },
    { day: 7, date: "Fri, 27 Nov", stay: "Taitung", moving: false, title: "East coast seafood day", plan: "Highway 11 coastal drive, Chenggong Fishing Harbor lunch and scenic stops. Sanxiantai is optional.", travel: "Rental car or private hire · full-day route TBD", note: "Aim to eat what is fresh and seasonal where local fishermen eat." },
    { day: 8, date: "Sat, 28 Nov", stay: "Tainan", moving: true, title: "Cross to the west coast", plan: "Long scenic TRA journey to Tainan, easy dinner and an evening stroll.", travel: "TRA · Taitung → Tainan · exact train TBD", note: "Keep arrival evening deliberately light." },
    { day: 9, date: "Sun, 29 Nov", stay: "Tainan", moving: false, title: "Coastal culture day", plan: "Qigu/Sicao area: Green Tunnel plus a tide-dependent clam, oyster or mudflat experience if operating.", travel: "Local driver/taxi · route and operator TBD", note: "Activity availability depends on tides and operator schedules." },
    { day: 10, date: "Mon, 30 Nov", stay: "Alishan area", moving: true, title: "Tea mountains", plan: "Travel via Chiayi. SunSweet House, tea scenery and Eryanping sunset are the current proposal.", travel: "Tainan → Chiayi by rail; private hire uphill · details TBD", note: "SunSweet is tentative and not booked." },
    { day: 11, date: "Tue, 1 Dec", stay: "Alishan", moving: true, title: "Into the forest", plan: "Transfer to the recreation area, check in and explore forest railway, giant trees and nearby trails.", travel: "SunSweet → Alishan transfer · pre-arrange taxi/private hire", note: "Chinshan is a leading option but not confirmed." },
    { day: 12, date: "Wed, 2 Dec", stay: "Alishan", moving: false, title: "Sunrise and ancient trees", plan: "Sunrise and sea of clouds if weather permits, followed by an unhurried full forest day.", travel: "Walking / forest railway / shuttle", note: "Weather-dependent dawn plan; exact sunrise transport TBD." },
    { day: 13, date: "Thu, 3 Dec", stay: "Taipei", moving: true, title: "Return to Taipei", plan: "Descend to Chiayi, take HSR north, settle in and enjoy an easy city evening.", travel: "Private transfer/taxi · Alishan → Chiayi; HSR → Taipei", note: "Final Taipei accommodation not yet confirmed." },
    { day: 14, date: "Fri, 4 Dec", stay: "Taipei", moving: false, title: "Zoo and Maokong", plan: "Full day for Taipei Zoo, Maokong Gondola, tea and mountain views.", travel: "MRT + gondola", note: "Check gondola maintenance dates and weather closer to travel." },
    { day: 15, date: "Sat, 5 Dec", stay: "Taipei", moving: false, title: "Friends, shopping and free time", plan: "Anime and 谷子 shops, bookstores, husband’s meetup and a generous unplanned block.", travel: "MRT / walking", note: "Neighbourhood and exact plans remain open." },
    { day: 16, date: "Sun, 6 Dec", stay: "Home", moving: true, title: "One last Taipei day", plan: "Late breakfast, final shopping, then airport transfer and evening flight home.", travel: "Flight · TPE → SIN · CI755 · 19:55–00:40 (+1)", note: "Allow ample airport time; flight arrives in Singapore after midnight." }
  ],
  places: [
    { location: "Hualien", icon: "🌊", name: "Qixingtan", chinese: "七星潭", status: "Must-do", type: "outdoor", description: "A broad pebble beach for sunrise, coastal walking and a relaxed first encounter with the Pacific.", duration: "1–2 hours", from: "Accommodation TBD · travel time TBD", map: "https://www.google.com/maps/search/?api=1&query=Qixingtan+Hualien" },
    { location: "Hualien", icon: "🪨", name: "Shitiping", chinese: "石梯坪", status: "Must-do", type: "outdoor", description: "Wild sea-eroded rock platforms and short exploratory walks; a different experience from Qixingtan.", duration: "1–1.5 hours", from: "Hualien city · roughly 1.5–2 hours by road (verify)", map: "https://www.google.com/maps/search/?api=1&query=Shitiping+Hualien" },
    { location: "Hualien", icon: "🐬", name: "Whale & dolphin watching", chinese: "賞鯨", status: "Weather dependent", type: "weather", description: "A possible bonus if late-November sea conditions are calm and an operator confirms sailing.", duration: "2–3 hours", from: "Harbour/operator TBD", map: "https://www.google.com/maps/search/?api=1&query=Hualien+whale+watching+harbor" },
    { location: "Chishang", icon: "🚲", name: "Brown Boulevard", chinese: "伯朗大道", status: "Must-do", type: "outdoor", description: "The trip’s signature relaxed cycling day, with stops for photos, snacks and the changing light.", duration: "2–4 hours", from: "Chishang stay · exact distance TBD", map: "https://www.google.com/maps/search/?api=1&query=Brown+Boulevard+Chishang" },
    { location: "Taitung", icon: "🐄", name: "Chulu Ranch", chinese: "初鹿牧場", status: "Interested", type: "tentative", description: "The chosen ranch experience for animals, open grassland and dairy treats.", duration: "2–4 hours", from: "Taitung-area stay · travel time TBD", map: "https://www.google.com/maps/search/?api=1&query=Chulu+Ranch+Taitung" },
    { location: "Taitung", icon: "🐟", name: "Chenggong Fishing Harbor", chinese: "成功漁港", status: "Must-do", type: "food", description: "A working fishing harbour for a fresh, affordable local seafood lunch and coastal atmosphere.", duration: "1.5–2 hours", from: "Taitung · roughly 1–1.5 hours by road (verify)", map: "https://www.google.com/maps/search/?api=1&query=Chenggong+Fishing+Harbor+Taitung" },
    { location: "Tainan", icon: "🛶", name: "Sicao Green Tunnel", chinese: "四草綠色隧道", status: "Must-do", type: "outdoor", description: "A mangrove boat trip that pairs naturally with the proposed coastal culture day.", duration: "1–2 hours", from: "Tainan stay · travel time TBD", map: "https://www.google.com/maps/search/?api=1&query=Sicao+Green+Tunnel+Tainan" },
    { location: "Tainan", icon: "🦪", name: "Clam / oyster experience", chinese: "挖蛤蜊／蚵田體驗", status: "Tentative", type: "tentative", description: "A hands-on coastal activity to add only if a suitable operator, tide and schedule align with the existing route.", duration: "Half day", from: "Qigu/Sicao operator and pickup TBD", map: "https://www.google.com/maps/search/?api=1&query=Qigu+Tainan+oyster+farm+experience" },
    { location: "Alishan", icon: "🌄", name: "Eryanping Trail", chinese: "二延平步道", status: "Interested", type: "tentative", description: "Tea-mountain views and a sunset opportunity if the proposed SunSweet night is confirmed.", duration: "1.5–2.5 hours", from: "SunSweet House · walkability/time to verify", map: "https://www.google.com/maps/search/?api=1&query=Eryanping+Trail+Alishan" },
    { location: "Alishan", icon: "🌲", name: "Alishan forest trails", chinese: "阿里山森林遊樂區", status: "Must-do", type: "outdoor", description: "Giant trees, Sister Ponds, forest railway and slow woodland walks over two nights in the park.", duration: "1–2 days", from: "Chinshan/Shermuh area · very close if booked", map: "https://www.google.com/maps/search/?api=1&query=Alishan+National+Forest+Recreation+Area" },
    { location: "Taipei", icon: "🐼", name: "Taipei Zoo", chinese: "臺北市立動物園", status: "Must-do", type: "outdoor", description: "A full family day with plenty of walking, paired with Maokong if energy and weather allow.", duration: "4–6 hours", from: "Final Taipei stay · travel time TBD", map: "https://www.google.com/maps/search/?api=1&query=Taipei+Zoo" },
    { location: "Taipei", icon: "🚠", name: "Maokong Gondola", chinese: "貓空纜車", status: "Interested", type: "weather", description: "Tea houses and city-to-mountain views after the zoo; operation depends on wind and maintenance.", duration: "2–4 hours", from: "Beside Taipei Zoo", map: "https://www.google.com/maps/search/?api=1&query=Maokong+Gondola" }
  ],
  food: [
    { icon: "🐟", name: "Sunfish", place: "Hualien · if responsibly available" },
    { icon: "🎋", name: "Bamboo tube rice", place: "Hualien / Indigenous cuisine" },
    { icon: "🍱", name: "Chishang bento", place: "Chishang" },
    { icon: "🦐", name: "Sakura shrimp", place: "Look out for it along the route" },
    { icon: "🐠", name: "Fresh harbour catch", place: "Chenggong, Taitung" },
    { icon: "🦪", name: "Oysters & clams", place: "Tainan coast" },
    { icon: "🐟", name: "Milkfish soup", place: "Tainan" },
    { icon: "🍤", name: "Shrimp rolls", place: "Tainan" },
    { icon: "🍵", name: "High-mountain tea", place: "Alishan" },
    { icon: "🥬", name: "Mountain vegetables", place: "Alishan" },
    { icon: "🥟", name: "Vegetable buns", place: "Breakfast shops / convenience stores" },
    { icon: "🍠", name: "Convenience-store sweet potato", place: "Anywhere — family ritual" }
  ],
  bookings: [
    { name: "China Airlines flights", status: "Confirmed", detail: "21 Nov: CI754 SIN 14:25 → TPE 19:05. 6 Dec: CI755 TPE 19:55 → SIN 00:40 (+1).", note: "Direct, full-service. Fare details are not displayed publicly on this site." },
    { name: "Jasper Young Hotel Banqiao", status: "Confirmed", detail: "21–22 Nov · family room for four · no breakfast.", note: "Free-cancellation deadline recorded as 7 Nov 2026; verify against the original booking confirmation." },
    { name: "Hualien stay", status: "Tentative", detail: "22–24 Nov · accommodation not selected.", note: "Prioritise neighbourhood convenience, room for four and access to the coast." },
    { name: "Chishang stay", status: "Tentative", detail: "24–26 Nov · accommodation not selected.", note: "Prefer a comfortable base near cycling and local food." },
    { name: "Taitung stay", status: "Tentative", detail: "26–28 Nov · accommodation not selected.", note: "Base choice depends on car/private-hire plan and hot-spring value." },
    { name: "Tainan stay", status: "Tentative", detail: "28–30 Nov · accommodation not selected.", note: "Old streets, local breakfast and access to coastal activities matter." },
    { name: "SunSweet House", status: "Tentative", detail: "Proposed for 30 Nov–1 Dec only.", note: "Price, quad-room availability, cancellation and transport not confirmed." },
    { name: "Alishan park stay", status: "Tentative", detail: "Proposed for 1–3 Dec · Chinshan and Shermuh remain candidates.", note: "Family room and cancellation terms need confirmation before booking." },
    { name: "Final Taipei stay", status: "Tentative", detail: "3–6 Dec · accommodation not selected.", note: "Needs convenient access for zoo, shopping, friends and airport transfer." }
  ]
};
